### Get Albums

GET http://localhost:8080/albums

### Get Single Album
GET http://localhost:8080/albums/1

### Add Album
POST http://localhost:8080/albums/addAlbum
Content-Type: application/json

{
    "title": "Test Album",
    "image": "/AlbumCovers/tyler_childers_-_purgatory.png",
    "artist": "Tyler Childers",
    "songs": [],
    "comments": []
}

### Delete Album
DELETE http://localhost:8080/albums/5/

### Delete Song
DELETE http://localhost:8080/songs/3/

### Add Song to Album
POST http://localhost:8080/albums/1/addSong
Content-Type: application/json

{
    "title": "I Swear (To God)",
    "songLength": "3:21",
    "artist": "Tyler Childers"
}

### Change song name
PATCH http://localhost:8080/songs/2

New Song Name

### Add Comment to Album
POST http://localhost:8080/albums/1/addComment
Content-Type: application/json

    {
        "author": "Kev",
        "review": "Album comment goes brrr..."
    }

### Get Comments
GET http://localhost:8080/comments
